### PR TITLE
Support patching of launcher Gradle template on Unity 2019.3 and newer.

### PR DESCRIPTION
**Pull request by Si1ver**
I want to start discussion on support for Unity 2019.3+ launcher Gradle template (see #337).

At the moment Unity will (in most cases) fail to build Gradle project in Unity editor 2019.3+ if Jetifier is enabled in project settings.

I've implemented support for patching `launcherTemplate.gradle` file.
I'm looking forward for your feedback to finish this PR or give up on this idea.

What's implemented:
1. Detection that `mainTemplate.gradle` is a library and not an application.
I decided that it's better to detect applied plugin type in `mainTemplate.gradle`.
We may check Unity editor version instead but I think it's error prone and we may unintentionly not support custom and preview builds of editor.
2. Injection of `// Android Resolver Repos Start ... // Android Resolver Repos End` in `launcherTemplate.gradle` or `mainTemplate.gradle` based on check described above.
3. We have to remove lines between `// Android Resolver Repos Start` and `// Android Resolver Repos End` in `mainTemplate.gradle` when there is a `launcherTemplate.gradle`.

What's still need to be implemented:
1. There are analytics events that have to be updated.

What to consider:
1. Unity 2019.3 with path version less than 2019.3.7 and 2020.1 with path version less than 2020.1.0b2 will still fail to build because of a bug with `launcherTemplate.gradle`.
This could be fixed when we will switch injection to post-process step as discussed in #308.

### CODE REVIEW

**Comment by Zifkan** [comment]
Any suggestion  when it will be released?

**Comment by Si1ver** [comment]
@Zifkan I hope ho have some progress on this PR this weekend.

I still have no reply from maintainers so I'm not sure if my implementation fits their expectations.

I've tested this path in one 2019.3 project and it seems to be working fine.

Cleaning up `mainTemplate.gradle` is critical for user experience and it should be implemented before merging this PR.

**Comment by Zifkan** [comment]
@Si1ver Can you share with me built package or explain how can i do it myself. I download project and used you changes in GradleTemplateResolver.cs but i have erros in project with Unity dependencies like "Unity" namespace and i dunno how to include it to project. Will be very helpful.
(можем в каком дискорде сконектиться)

**Comment by Si1ver** [comment]
@Zifkan I sent you an email with my Discord user name.

**Comment by Si1ver** [comment]
@stewartmiles Hey. I think I'm ready for review.

**Comment by leni8ec** [comment]
For those who are looking for a temporary solution:
1. Enable `Custom Gradle Properties Template` in `Unity -> BuildSettings -> PublishingSettings`
2. Add this strings to `Assets/Plugins/Android/gradleTemplate.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```

3. Disable `UseJetifier` in **Android Resolver** config (_optional_)

Success!

P.S. if you are used **_Multidex_** - move it's entries from MainGradle to LauncherGradle ([link](https://forum.unity.com/threads/cant-build-with-multidex-enabled.773348/#post-5693968))


> Unity v2019.3.11, EDM v1.2.153. (worked for Appodeal and Firebase depandencies)

**Comment by ewnu** [comment]
This PR Should get some attention!
I've been waiting for a long time.

**Comment by Si1ver** [comment]
I've tested this on top of 1.2.155 and build a release of my app using this patch. This PR still need to be reviewed by developers. Analytics events should be updated by them, I can't do it by myself.

Also I'm ready to implement any changes if needed. :)

**Comment by chkuang-g** [comment]
@Si1ver 

Sorry for the late reply.  We are currently looking into new customization in Unity 2019.3+ and this is a pretty good improvement. 

I'll review  and test this in the next view days.

Thank you for the contribution!

**Comment by Si1ver** [comment]
Hey. It's alright :) I'll be happy to make any changes if needed. But I'm out of the city till Monday.

**Comment by chkuang-g** [comment]
No problem. I would recommend to rebase/merge to the current version of EDM4U just in case.  I made a couple of changes to  `GradleTemplateResolve.cs` in 1.2.151 and I saw your change is based on 1.2.150.

https://github.com/googlesamples/unity-jar-resolver/commit/ed6e2dbdb5c4ee29a4f1d2213c50a670c4a6a048

**Comment by vimanyu** [comment]
Hi @Si1ver,
I just started looking at this request and wanted to clarify a few things.

We rolled out a feature in EDM4u sometime ago that injects androidx and jetifier properties into the gradle.properties for Unity versions >=2019.3.
https://github.com/googlesamples/unity-jar-resolver/commit/13a530595241b4781b090c975e87186ddbd79b49

Does this change cover your use case or are you also planning to use the launcher template for injecting other dependencies?

**Comment by Si1ver** [comment]
Hey @vimanyu

I've rebased my PR a few days ago to update EDM4U in my project. Actually I haven't tested it without my change.

I will test EDM4U without my patch and reach back with more info.

**Comment by Si1ver** [comment]
Hey @vimanyu

I've checked that EDM4U v. 1.2.163 works fine in my project (without my patch). Unity is able to build project without any errors and I can't see any problems in produced android application.

Also I've checked that we have no need to use the launcher template for injecting other dependencies.
I'm not sure if injecting to launcher template was my take on solving the problem or I had some dependencies that were requiring that.

Thanks!

**Comment by vimanyu** [comment]
Awesome! Thanks @Si1ver for running these tests and confirming this works for your case.
I am closing this ticket for now.

**Pull request closed without merging**
