### PR TITLE
Fix for issue #79.

### PR DESCRIPTION
**Pull request by JimmyDeemo**
Check if the version control provider is active and enabled, and check out the file if so.

### CODE REVIEW

**Comment by JimmyDeemo** [comment]
I signed it!

**Comment by stewartmiles** [comment]
Thanks for the patch @JimmyDeemo it looks like our CLA bot doesn't like your signature.  I had a look at the internal dashboard and it says your email domain is a local address e.g `foo@XXXX-macbook-pro.local` .  I'm guessing that it wants a real email address that is associated with this commit and that you set your identity in git to correctly add your ID to the commit https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup .

**Comment by tommikiviniemi-srs** [comment]
Hi Jimmy.

Please consider adding an online check such as:

public static bool ShouldUseVersionControl() {
	return UnityEditor.VersionControl.Provider.enabled &&
		UnityEditor.VersionControl.Provider.isActive &&
		(!UnityEditor.VersionControl.Provider.requiresNetwork || UnityEditor.VersionControl.Provider.onlineState == UnityEditor.VersionControl.OnlineState.Online);
}

**Comment by JimmyDeemo** [comment]
Understood. I will look to rectify these things in the coming days.

@tommikiviniemi-srs, are you aware of any examples for version control code? I’m finding the documentation lacking.

**Comment by tommikiviniemi-srs** [comment]
Hi Jimmy. No it’s hardly documented at all, at least last I checked.

**Comment by JimmyDeemo** [comment]
I added the checks that @tommikiviniemi-srs suggested, used them verbatim, hope that's OK.

This works for me locally (checks out the file when saving it), but will only apply to the settings file. It's the only one i've had issues with.

**Comment by stewartmiles** [comment]
Looks, cool I'll merge it and we'll see what breaks and who complains ;)

**Comment by JimmyDeemo** [comment]
FYI, I have just noticed that the same thing happens to `AndroidResolverDependencies.xml` but this only appears as a warning. I will look to make a new pull request for this.

**Pull request merged**
