### PR TITLE
Do not explode AARs even if gradle project is not enabled

### PR DESCRIPTION
**Pull request by doterax**
Fixes googlesamples/unity-jar-resolver#584 googlesamples/unity-jar-resolver#287

### CODE REVIEW

**Comment by ievgenmukhin** [comment]
This fix will be extremely helpful for our projects.

**Review by chkuang-g — APPROVED** [review]

**Comment by chkuang-g** [comment]
Hey @doterax 

Sorry have to revert this change in #612 since it is failing tests.

Let me put together a new PR

**Comment by chkuang-g** [comment]
Here is the new PR. I will add you guys to review and wait for a week or two for your feedback :)

**Comment by doterax** [comment]
I reviewed new PR

**Pull request merged**
