### PR TITLE
Unity now supports x86_64 for Android apps on Chrome OS. Add it to th…

### PR DESCRIPTION
**Pull request by davidrogers-unity**
To resolve issue #461. x86_64 support for Android projects.

### CODE REVIEW

**Comment by davidrogers-unity** [comment]
I have signed a CLA now. But I don't know how to get it to recheck.

**Review by chkuang-g — CHANGES_REQUESTED** [review]
Looks reasonable.  And does not seems to break anything prior to 2020.3.17 :)

Could you also update the comment here, just to keep doc up-to-date?
https://github.com/googlesamples/unity-jar-resolver/blob/41072ec47290642e126388ae3c5dd43d42695d9b/source/AndroidResolver/src/AndroidAbis.cs#L242

**Comment by davidrogers-unity** [comment]
Good call and that made me think about something. We will only be supporting x86_64 from 2019.4+. Do we need to do any special handling for that? Or will everything work fine even if the architecture support doesn't exist in Unity from 2017.4-2019.3?

**Comment by chkuang-g** [comment]
That probably would not be an issue since this block of code tested if the enum exists.
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/AndroidResolver/src/AndroidAbis.cs#L80

Unless the enum exists in certain version Unity which has not support ChromeOS yet. :/

The worst case is that EDM4U will not [strip away unused abi](https://github.com/googlesamples/unity-jar-resolver#abi-stripping), ex. `x86_64`, which may make the the apk size bigger.

**Comment by chkuang-g** [comment]
Second thought, I wonder if Android would load the correct library when both `x86` and `x86_64` libraries are presented...

**Comment by davidrogers-unity** [comment]
It should, right? I think the libraries are chosen based on their directory name matching the current ABI.

**Review by chkuang-g — APPROVED** [review]

**Pull request merged**
