### PR TITLE
use AGP version as condition check

### PR DESCRIPTION
**Pull request by argzdev**
Possible fix for #699 

Adding the plugin repositories in `settingsTemplate.gradle` and `mainTemplate.gradle` condition checker will be based on the AGP version instead of the Unity Editor version.

### CODE REVIEW

**Comment by manugildev** [comment]
In order to test, please download `2021.3.42f1` from [`unityhub://2021.3.42f1/f1197811e8ce`](unityhub://2021.3.42f1/f1197811e8ce) (copy paste into your browser navigation bar).

**Comment by argzdev** [comment]
Thanks for the heads up, @manugildev. From my understanding, shouldn't this fix also work for version `2021.3.41f1` since the mapped AGP version is >= 7.0?

**Comment by manugildev** [comment]
> Update: We're running some tests with this fix, but it still encounters the same issue.

Yes, `2021.3.41f1` had a bug where **DIR_UNITYPROJECT** on the `settingsTemplate.gradle` is not being replaced by the actual directory. This might be causing an issue. It's fixed for `2021.3.42f1`, but as you said, since it's officially released next week that version is still missing the JDK requirements.

While we wait for `2021.3.42f1` to be fully publicly released next week, could you check in `2021.3.41f1` if manually replacing `**DIR_UNITYPROJECT**` in `settingsTemplate.gradle` by the actual directory of the project solves the issue?

**Comment by manugildev** [comment]
> Update: We're running some tests with this fix, but it still encounters the same issue.

@argzdev  Yes, `2021.3.41f1` had a bug where `**DIR_UNITYPROJECT**` on the `settingsTemplate.gradle` is not being replaced by the actual directory. This might be causing an issue. It's fixed for `2021.3.42f1`, but as you said, since it's officially released next week that version is still missing the JDK requirements.

While we wait for `2021.3.42f1` to be fully publicly released next week, could you check in `2021.3.41f1` if manually replacing `**DIR_UNITYPROJECT**` in `settingsTemplate.gradle` by the actual directory of the project solves the issue?

Just to clarify there are two issues with `2021.3.41f1` (AGP 7.4.2) at the moment:
 - The repositories section needs to be put in `settingsTemplate.gradle`, this is solved by your changes in unity-jar-resolver.
 - `**DIR_UNITYPROJECT**` is not being replaced by the actual directory during build/export time. This is solved by Unity in next release 2021.3.42f1.  

Thank you for your help!

**Comment by a-maurice** [comment]
I ended up doing this change with this PR, so that I could get the release out faster with it.  https://github.com/googlesamples/unity-jar-resolver/pull/702

Thanks for setting it up, and testing it out on your end.

**Comment by a-maurice** [comment]
@manugildev Good to hear.  I can't share any firm dates, but the next releases should have the latest EDM4U version.  The Firebase Unity SDK should be out soon.

**Pull request closed without merging**
